load("@rules_cc//cc:defs.bzl", "cc_test")


cc_test(
    name = "transfer_test",
    srcs = ["transfer_test.cc"],
    deps = [
        "//src/lib:TRANSFERLib",
        "@googletest//:gtest_main",
    ],
)
